name: MERN CI

on:
  push:
    branches: [ main ]

jobs:
  backend-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - "27017:27017"
        env:
          PORT: ${{ secrets.PORT }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Debug Directory Structure
        run: |
          ls -R
          ls -la backend || echo "backend not found"
          ls -la backend/Services || echo "backend/Services not found"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Waiting for MongoDB to be ready
        run: |
          until nc -z localhost 27017; do
            echo "Waiting for MongoDB..."
            sleep 2
          done
          echo "MongoDB is ready!"

      - name: Install dependencies
        run: |
          cd backend/Services/AuthServices
          npm install

      - name: Seed MongoDB
        env:
          MONGO_URI: mongodb://localhost:27017/auth-service-test
        run: |
          cd backend/Services/AuthServices
          node Src/seedTasksData.js

      - name: Run tests
        env:
          MONGO_URI: mongodb://localhost:27017/auth-service-test
          NODE_ENV: test
        run: |
          cd backend/Services/AuthServices
          npm test
